/* eslint-disable max-len */
module.exports = [{
  type: 'road',
  prompt: 'A woman with wild hair and eyes blocks the road. She\'s says Incan prophecies point to 11:45am, today, as the apocalypse.',
  live_option: 'Ask her about other timezones',
  live_message: 'The woman stares at you, transfixed, perplexed. You walk on by.',
  death_option: 'Tell her you are an angel from the alien planet Morloch and you need through',
  death_message: 'She puts a hex on you and tries to cast you off the Earth. You lose 3 minutes.',
  consequence: 3,
}, {
  type: 'road',
  prompt: 'You see a handwritten sign in the road. "Call 1-800-ISL-EGIT for free tacos and solar glasses."',
  death_option: 'Think about tacos; keep on driving',
  death_message: 'You find yourself at a Taco Bell drive thru. You lose 2 minutes.',
  live_option: 'Call the number',
  live_message: 'The man on the phone convinces you to buy 12, limited edition shnorkisbergs. You\'re not sure what they do.',
  consequence: 2,
}, {
  type: 'road',
  prompt: 'You notice a bad wreck up ahead. Paramedics are loading a man onto a stretcher. A glint of sunlight catches your eye. On the dashboard of the wrecked car sit a pair of solar glasses.',
  death_option: 'Park nearby and try to steal the glasses',
  death_message: 'Paramedics mistake you for a faith healer. They all wait expectantly. You lose 3 minutes.',
  live_option: 'You\'re not that desperate; drive on past',
  live_message: '+2 imaginary Karma Points.',
  consequence: 3,
}, {
  type: 'road',
  prompt: 'Traffic is backed up, horribly. Lots of out-of-towners here to see the eclipse.',
  death_option: 'Relax; put some tunes on',
  death_message: 'You fall asleep to Celine Deon. You lose 2 minutes.',
  live_option: 'Lay on your horn like you\'ve never laid on it, before',
  live_message: 'The other cars run you off the road. You find there\'s less traffic, here.',
  consequence: 2,
}, {
  type: 'road',
  prompt: 'You get a text message while driving. It could be about solar glasses.',
  death_option: 'Check it',
  death_message: 'It\'s 2 hours later. You checked Facebook, Twitter, email, and Instagram. You missed the eclipse.',
  live_option: 'Try to tell Siri to read it back to you',
  live_message: 'Siri buys you a box of chocolates.',
  consequence: 120,
}, {
  type: 'road',
  prompt: 'There\'s a "road closed" sign ahead. Turning around won\'t be easy.',
  death_option: 'Turn around',
  death_message: 'It was a trap. Aliens abduct you. You lose 5 minutes.',
  live_option: 'Ram through the sign',
  live_message: 'There was radioactive material on the other side. You now have butterfly wings.',
  consequence: 5,
}, {
  type: 'road',
  prompt: 'You hear a strange knocking sound coming from the engine. There\'s not much time left before the eclipse, but the sound is worrying you.',
  death_option: 'Pull over and pop the hood',
  death_message: 'A gnome was trapped in your engine. He sends you back in time as thanks for freeing him. You gain 5 minutes.',
  live_option: 'Keep driving',
  live_message: 'The noise goes away. You\'ll never know what it was.',
  consequence: -6,
}, {
  type: 'road',
  prompt: 'A delivery truck speeds by you. The logo on the side reads, "Solar Eclipse Glass Manufacturing Co."',
  death_option: 'Call the "How\'s my driving?" number to complain about it going 35 in a 30',
  death_message: 'You get stuck in "Hold Hell." You lose 4 minutes.',
  live_option: 'Race it down, Mad Max style',
  live_message: 'You win! You forget what you were racing for.',
  consequence: 4,
}, {
  prompt: 'You see an elderly woman wearing a pair of solar glasses.',
  death_option: 'Ask the nice lady where she got them from',
  death_message: 'As the woman is about to answer, she is swallowed up by the earth. You spend 2 minutes explaining to police what happened.',
  live_option: 'Steal them and run',
  live_message: 'Beams of energy burst from the woman\'s eyes. She is one of the X-Men. You quickly hand her glasses back.',
  consequence: 2,
}, {
  prompt: 'You see a taco shop.',
  death_option: 'Move on. No time for tacos.',
  death_message: 'There\'s always time for tacos. Arbitrarily lose 5 minutes.',
  live_option: 'Get in a debate with the owner over hard shells vs. soft shells.',
  live_message: 'There is no debate. Soft shells are obviously superior.',
  consequence: 5,
}, {
  prompt: 'People are lined up out the door of the local car dealership. A sign outside reads, "Free solar glasses inside."',
  death_option: 'Get in line',
  death_message: 'You got in the wrong line. You are now the proud owner of a 2007 Chrysler Sebring. You lose 3 minutes.',
  live_option: 'Keep moving; no telling how long that line will take',
  live_message: 'The line clears up as soon as you leave.',
  consequence: 3,
}, {
  prompt: 'A man in an alley approaches you. "Psst. I know what you\'re looking for." He looks around left and right to see if anyone is looking.',
  death_option: 'Back away and tell the man you\'re not interested',
  death_message: 'You back into an open manhole. You lose a minute.',
  live_option: 'See what he has to offer',
  live_message: 'The man goes down on one knee and holds up a ring. You blush. People are staring. You say, "Yes! A thousand times, yes!"',
  consequence: 1,
}, {
  prompt: 'You remember about your neighborhood\'s "Nextdoor" app, a place for all the cranky and unbalanced members of your community.',
  death_option: 'Ask where you can get solar glasses',
  death_message: 'You receive 10,000 replies about how you should have though that sooner. You lose 1 minute.',
  live_option: 'Complain about generalized hooliganism',
  live_message: 'You get tickets to the opera.',
  consequence: 1,
}, {
  prompt: 'A girl scout is handing out handfuls of solar glasses to passersby.',
  death_option: 'Run up and ask her for a handful',
  death_message: 'You trip and are sucked into a time vortex. It is now 1 minute ago.',
  live_option: 'Run up and ask her for one',
  live_message: 'She runs out of glasses before you get to her.',
  consequence: -2,
}, {
  prompt: 'People mill about the local park waiting for the eclipse to happen. They\'re all wearing solar glasses.',
  death_option: 'Offer $1,000 for the first person to give you solar glasses',
  death_message: 'Gandalf turns you into a toad. Wait, what? Lose 3 minutes.',
  live_option: 'Ask if anyone has any to spare',
  live_message: 'You get handed some loose change.',
  consequence: 3,
}, {
  prompt: 'You feel the energy draining out of you. You feel like it\'s been years since you last drank a cup of coffee.',
  death_option: 'Coffee? Gross.',
  death_message: 'Your loss.',
  live_option: 'Single origin, freshly ground, medium-roast coffee slow poured into a V60 at precisely 205 degrees farenheit for exactly 3 minutes and 22 seconds. Not a second more. Not a second less.',
  live_message: 'You choke on something. Someone left solar glasses in your coffee. You win!',
  win_state: true,
  consequence: 0,
}]
/* eslint-enable max-len */
